# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure:             https://github.com/Azure/actions

name: deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url:  ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache Node.js modules
        id:   cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key:  ${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run:  npm ci

      - name: Check for only in tests
        run:  npm run stop-only

      - name: Deploy to Azure Web App
        id:   deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name:        nisinoon
          slot-name:       Production
          package:         .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C789F3DAFFFF45EA89AA17889914203C }}